### ISSUE TITLE
Error during the build phase of an Android application

### ISSUE THREAD

**Issue by david-azancot** [4d/android-ProjectGenerator#4]
## What did you do?

- Build Android project from the 4D mobile project editor

## What did you expect to happen?

- The Android simulator should have launched, and the application should have opened.

## What happened instead?

- Received this error message during the build phase :

`Failed to generate files
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property deepLink has not been initialized
    at kscript.scriplet.ProjectEditor.getDeepLink(Main.kt:2360)
    at kscript.scriplet.MustacheHelper.<init>(Main.kt:754)
    at kscript.scriplet.GenerateCommand.start(Main.kt:8647)
    at kscript.scriplet.GenerateCommand.run(Main.kt:8602)
    at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
    at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
    at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
    at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
    at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
    at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
    at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
    at kscript.scriplet.MainKt.main(Main.kt:8768)`

### Environment

- 4D 20R3.287689
- Android studio Giraffe
- Pixel 4 (simu) 
- macOS Ventura 13.3.1
- 4D-Mobile-App Compiled version [latest release](https://github.com/4d/4D-Mobile-App/releases/latest) (20.0.3)

**Comment by e-marchand** [comment]
je reproduit qu'en desactivant le deep linking dans le flag

This.project.hasAndroidDeepLinking:=Feature.with("androidDeepLinking")


le code semble ne pas être compatible avec sa désactivation
https://github.com/4d/android-ProjectGenerator/blob/1c85ab36b964a78e432231542a85bf8b1fee81bb/ProjectEditor.kt#L73

maintenant pourquoi c'est pas activé chez vous la feature?
vous avez pas un fichier de conf 4d mobile?

**Comment by e-marchand** [comment]
finalement j'ai trouvé une piste, comme quoi si vous prenez le composant source avec la v20 ou la main avec le composant compilé peut être on active pas les features

j'active donc differement les features https://github.com/4d/4D-Mobile-App/commit/6e7672eb6daf9fe26abaa060570b297d7ca2d98b (en main et à reporter)

et ici par contre le code devrait être différent pour supporter la feature désactivé
